"""cambios en ovejas

Revision ID: 336276ca4bbb
Revises: 340e29ed7826
Create Date: 2024-08-06 15:02:31.528679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336276ca4bbb'
down_revision = '340e29ed7826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oveja', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('sexo',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('Macho', 'Hembra', name='sexo_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oveja', schema=None) as batch_op:
        batch_op.alter_column('sexo',
               existing_type=sa.Enum('Macho', 'Hembra', name='sexo_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
