"""Agregar campos compra_id y venta_id a Finanzas

Revision ID: 40d39e52aedf
Revises: 50797d558dc2
Create Date: 2024-09-29 19:35:56.825069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d39e52aedf'
down_revision = '50797d558dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finanzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compra_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('venta_id', sa.Integer(), nullable=True))
        
        # Agregar nombres a las claves foráneas
        batch_op.create_foreign_key('fk_finanzas_compra_id', 'compras', ['compra_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_finanzas_venta_id', 'ventas', ['venta_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finanzas', schema=None) as batch_op:
        # Eliminar las restricciones de clave foránea usando sus nombres
        batch_op.drop_constraint('fk_finanzas_compra_id', 'finanzas', type_='foreignkey')
        batch_op.drop_constraint('fk_finanzas_venta_id', 'finanzas', type_='foreignkey')
        batch_op.drop_column('venta_id')
        batch_op.drop_column('compra_id')

    # ### end Alembic commands ###
