"""empty message

Revision ID: 75800bef2f14
Revises: de29c565c861
Create Date: 2024-09-18 16:57:23.814912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75800bef2f14'
down_revision = 'de29c565c861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finanzas', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finanzas', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###
