"""ajustar modelo finanzas

Revision ID: de29c565c861
Revises: 74aaf892465c
Create Date: 2024-09-18 16:23:00.748549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de29c565c861'
down_revision = '74aaf892465c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finanzas', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=10),
               type_=postgresql.ENUM('Venta', 'Compra', name='tipo_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finanzas', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=postgresql.ENUM('Venta', 'Compra', name='tipo_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
